<a href="https://colab.research.google.com/github/SuelenRuiz/Python/blob/main/UNINTER_Bibliotecas_NUMPY_e_PLOTLY_Mat%C3%A9ria_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - 1 Abrir a Documentação

# NUMPY - 2 Qual a diferença do array NUMPY para list em Python?

In [1]:
import numpy as np
num_elementos = 100000000

# lista_elementos=[]
# for x in range(num_elementos):
#   lista_elementos.append(x)
# print(lista_elementos[-1])

array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

99999999


# NUMPY - 3 Criação de arrays em numpy

In [2]:
array_teste = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'Criação de array numpy utilizando o método .array:\n{array_teste}\n')

# Comando alt + shift + down para copiar linha de cima:

print(f'Criação de array numpy utilizando o método .array:\n{np.array([0,1,2,3,4,5,6,7,8,9])}\n')
print(f'Criação de array numpy utilizando o método .ones:\n{np.ones([9])}\n')
print(f'Criação de array numpy utilizando o método .zeros:\n{np.zeros([9])}\n')
print(f'Criação de array numpy utilizando o método .arange:\n{np.arange(9)}\n')
print(f'Criação de array numpy utilizando o método .linspace:\n{np.linspace(0,40,num=41)}\n')
print(f'Criação de array numpy utilizando o método .linspace:\n{np.linspace(0,40)}\n')




Criação de array numpy utilizando o método .array:
[0 1 2 3 4 5 6 7 8 9]

Criação de array numpy utilizando o método .array:
[0 1 2 3 4 5 6 7 8 9]

Criação de array numpy utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1.]

Criação de array numpy utilizando o método .zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0.]

Criação de array numpy utilizando o método .arange:
[0 1 2 3 4 5 6 7 8]

Criação de array numpy utilizando o método .linspace:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40.]

Criação de array numpy utilizando o método .linspace:
[ 0.          0.81632653  1.63265306  2.44897959  3.26530612  4.08163265
  4.89795918  5.71428571  6.53061224  7.34693878  8.16326531  8.97959184
  9.79591837 10.6122449  11.42857143 12.24489796 13.06122449 13.87755102
 14.69387755 15.51020408 16.32653061 17.14285714 17.95918367 18.7755102
 19.59183673 20.40816327 21.2244898  22.04081633 2

In [3]:
# Mesmo resultado, porém, formas diferentes de criar um vetor usando numpy:
vetor1 = np.arange(5)
vetor2 = np.array([0,1,2,3,4])
print(vetor1)
print(vetor2)

[0 1 2 3 4]
[0 1 2 3 4]


# NUMPY - 4 A importância de se definir o tipo de dado

In [4]:
import numpy as np
num_elementos = 1000000000
array_performance=np.zeros(num_elementos, dtype=np.int32)
array_performance

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

# NUMPY - 5 Criação de números randômicos

In [5]:
import numpy as np

rng=np.random.default_rng()
print(rng.random(10))

[0.68664945 0.50410116 0.56080003 0.29017974 0.80537815 0.18696629
 0.59210093 0.94470903 0.18127974 0.3828513 ]


# NUMPY - 6 Vetor, Matriz, Tensor

In [ ]:
import numpy as np

rng= np.random.default_rng()
vetor = rng.random(4)
print(f'Array de 1 dimensão (VETOR) randômico:\n{vetor}\n')
matriz = rng.random([4,4])
print(f'Array de 2 dimensões (MATRIZ) randômico:\n{matriz}\n')

#Um tensor é um array multidimensional. Portanto, um exemplo seria o arquivo NetCDF

tensor = rng.random([4,4,4])
print(f'Array de 3 dimensões (TENSOR) randômico:\n{tensor}\n')

tensor_2 = rng.random([4,4,4,4])
print(f'Array de 4 dimensões (TENSOR) randômico:\n{tensor_2}\n')



# NUMPY - 7 Ordenação e Adição de elementos

In [42]:
import numpy as np

rng=np.random.default_rng(seed=42)

array_1= rng.random([2,3])

print(f'Array 1 SEM ordenação: \n{array_1}\n')
print(f'Array 1 COM ordenação - ordenado por linha: \n{np.sort(array_1)}\n')
print(f'Array 1 COM ordenação - ordenado por coluna: \n{np.sort(array_1, axis=0)}\n')


# Contatenação

array_2=rng.random([2,1])
print(f'Array2:\n{array_2}\n')

array_concatenado = np.concatenate([array_1, array_2], axis=1)
print(f'Array concatenado:\n{array_concatenado}\n')

array_concatenado_2=np.hstack([array_1,array_2])
print(f'Array concatenado com hstack:\n{array_concatenado_2}\n')


Array 1 SEM ordenação: 
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]

Array 1 COM ordenação - ordenado por linha: 
[[0.43887844 0.77395605 0.85859792]
 [0.09417735 0.69736803 0.97562235]]

Array 1 COM ordenação - ordenado por coluna: 
[[0.69736803 0.09417735 0.85859792]
 [0.77395605 0.43887844 0.97562235]]

Array2:
[[0.7611397 ]
 [0.78606431]]

Array concatenado:
[[0.77395605 0.43887844 0.85859792 0.7611397 ]
 [0.69736803 0.09417735 0.97562235 0.78606431]]

Array concatenado com hstack:
[[0.77395605 0.43887844 0.85859792 0.7611397 ]
 [0.69736803 0.09417735 0.97562235 0.78606431]]

O número de linhas do array concatenado é: 2
O número de linhas e colunas do array concatenado é: (2, 4)
O número total de elementos do array concatenado é: 8


# NUMPY - 8 Conhecendo seu Array

In [46]:
import numpy as np

rng=np.random.default_rng(seed=42)

array_3= rng.random([23,43,17])

print(f'O número de linhas do array é: {len(array_3)}')
print(f'O número de linhas e colunas do array, ou seu formato, é: {array_3.shape}')
print(f'O número total de elementos do array é: {array_3.size}')
print(f'O tipo de dado do array é: {array_3.dtype}')
print(f'O tipo de dado do array é: {type(array_3)}')
print(f'Quais são suas dimensões? {array_3.ndim}')

O número de linhas do array é: 23
O número de linhas e colunas do array, ou seu formato, é: (23, 43, 17)
O número total de elementos do array é: 16813
O tipo de dado do array é: float64
O tipo de dado do array é: <class 'numpy.ndarray'>
Quais são suas dimensões? 3


# NUMPY - 9 Como mudar um formato de array

In [77]:
import numpy as np

array_a= np.arange(0,20)
print(f'Array a: \n{a}\n')

# Duas formas diferentes de mudar o formato o array:

array_a = array_a.reshape(4,5)
print(f'Array a com formato alterado: \n{array_a}\n')

array_a = np.reshape(array_a,[4,5])
print(f'Array a com formato alterado: \n{array_a}\n')

# Para achar a matriz:

array_a = array_a.flatten()
print(f'Array a com formato alterado: \n{array_a}\n')

array_b = array_a.reshape(4,5)
print(f'Array b: \n{array_b}\n')

array_b = np.vsplit(array_b, 4)
print(f'Array b com formato alterado: \n{array_b}\n')



Array a: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array a com formato alterado: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array a com formato alterado: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array a com formato alterado: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array b: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array b com formato alterado: 
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]



In [78]:
print(array_b[0])

[[0 1 2 3 4]]


# NUMPY - 11 Salvando um array num arquivo txt

In [114]:
import numpy as np

x = np.arange(27)
x = x.reshape((3,3,3))
print(f'tensor 3x3x3:\n {x}')

y = x.flatten()
print(f'\n vetor de 27 posições:\n {y}')
np.savetxt('arrayTeste.txt', y,fmt= '%d', delimiter = ';')

z= np.loadtxt('arrayTeste.txt',dtype = np.int8 ,delimiter = ';',)

print(f'\n arquivo recuperado e carregado para dentro do programa:\n {z} \ncom o seguinte tipo de dado: {(z.dtype)}')

tensor 3x3x3:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

vetor de 27 posições:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

arquivo recuperado e carregado para dentro do programa:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 
com o seguinte tipo de dado: int8


# PLOTLY - 1 Abrir Documentação

# PLOTLY - 2 Criando arrays para montar

In [ ]:
import numpy as np

a = 3/4
b = 2/4
c = 1/4
vetor_a=np.ones(20)
vetor_b=np.ones(20)
vetor_c=np.ones(20)

for i in range(1,20):
  vetor_a[i]=vetor_a[i-1]+a**i
  vetor_b[i]=vetor_b[i-1]+b**i
  vetor_c[i]=vetor_c[i-1]+c**i
print(vetor_a)
print(vetor_b)
print(vetor_c)

np.savetxt('vetor_a.txt', vetor_a, fmt='%f', delimiter=';')
np.savetxt('vetor_b.txt', vetor_b, fmt='%f', delimiter=';')
np.savetxt('vetor_c.txt', vetor_c, fmt='%f', delimiter=';')


# PLOTLY - 3 Criando nosso primeiro gráfico

In [117]:
import numpy as np
import plotly.express as px

array_a = np.loadtxt('vetor_a.txt', dtype=np.float64, delimiter=';')
array_b = np.loadtxt('vetor_b.txt', dtype=np.float64, delimiter=';')
array_c = np.loadtxt('vetor_c.txt', dtype=np.float64, delimiter=';')

print(array_a)


array_abc = np.vstack([array_a, array_b, array_c])
print(array_abc)
array_abc = array_abc.transpose()
print(array_abc)
fig=px.scatter(array_abc)
fig.show()

[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
 3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
 3.969932 3.977449 3.983087 3.987315]
[[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
  3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
  3.969932 3.977449 3.983087 3.987315]
 [1.       1.5      1.75     1.875    1.9375   1.96875  1.984375 1.992188
  1.996094 1.998047 1.999023 1.999512 1.999756 1.999878 1.999939 1.999969
  1.999985 1.999992 1.999996 1.999998]
 [1.       1.25     1.3125   1.328125 1.332031 1.333008 1.333252 1.333313
  1.333328 1.333332 1.333333 1.333333 1.333333 1.333333 1.333333 1.333333
  1.333333 1.333333 1.333333 1.333333]]
[[1.       1.       1.      ]
 [1.75     1.5      1.25    ]
 [2.3125   1.75     1.3125  ]
 [2.734375 1.875    1.328125]
 [3.050781 1.9375   1.332031]
 [3.288086 1.96875  1.333008]
 [3.466064 1.984375 1.333252]
 [3.599548 1.992188 1.333313]
 [3.699661 1.996

# PLOTLY - 5 Utilizando plotly.graph_objects

In [119]:
import numpy as np
import plotly.graph_objects as go
array_a_axis_y = np.loadtxt("vetor_a.txt",dtype=np.float64, delimiter= ';')
array_b_axis_y = np.loadtxt("vetor_b.txt",dtype=np.float64, delimiter= ';')
array_c_axis_y = np.loadtxt("vetor_c.txt",dtype=np.float64, delimiter= ';')

array_axis_x = np.arange(1,array_a_axis_y.size)
fig = go.Figure()
fig.add_trace(go.Scatter(x= array_axis_x, y= array_a_axis_y,mode='lines', name='Série de 3/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_b_axis_y,mode='markers', name='Série de 2/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_c_axis_y,mode='markers+lines', name='Série de 1/4'))
fig.update_layout(title = "Somatório de Series com frações",
                  xaxis_title = "termos",
                  yaxis_title = "valor")
fig.show()